services:
  #######################################################
  #  Rabbitmq
  #######################################################
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
      # volumes:
      #   - rabbitmq:/var/lib/rabbitmq
    networks:
      - emtt

  #######################################################
  #  Postgress
  #######################################################
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - emtt

  #######################################################
  #  Jaeger
  #######################################################
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    user: root
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5775:5775/udp
      - 5778:5778
      - 4317:4317
      - 4318:4318
      - 16686:16686
      - 14269:14269
      - 9411:9411
    environment:
      - MEMORY_MAX_TRACES=100000
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger_data:/badger
    networks:
      - emtt

  #######################################################
  #  identity-service
  #######################################################
  identity:
    container_name: identity
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: src/identity
    ports:
      - "3311:3311"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
    networks:
      - emtt

  #######################################################
  #  profile-service
  #######################################################
  profile:
    container_name: profile
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: src/profile
    ports:
      - "3322:3322"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
    networks:
      - emtt

volumes:
  jaeger_data:

networks:
  emtt:
